<?php 
// application/layouts/scripts/layout.phtml

echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <title>Bloggers turns to developers</title>
  <?php echo $this->headLink()->appendStylesheet('/quickstart/public/css/global.css') ?>
  <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/main.css'); ?>
</head> 
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b><a href="<?php echo $this->baseurl(); ?>">ZF Quickstart Application</a></b>&nbsp; &nbsp; 
        <a href="<?php 
        if( Zend_Auth::getInstance()->hasIdentity() ) { 
        	$str = "/index/logout";
        	$log = "Logout";  
       	} else { 
       		$str = "/index/login";
       		$log = "Login";  
       	} 
       	echo $this->baseurl().$str; ?>"><?php echo $log; ?></a>
    </div>    
</div>

<div><?php echo $this->layout()->content ?></div>

</body>
</html>
